KPMGTest/Controllers/FileUploadController.cs
using KPMGTest.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Spatial;
using System.Web;
using System.Web.Mvc;
using KPMG.Core.Contract;
using KPMG.Data.DAL;
using KPMG.DataProcess;
using PagedList;

namespace KPMGTest.Controllers
{
    public class FileUploadController : Controller
    {

        private IGetData data;
        private IValidateData invalidator;
        

        public FileUploadController(IGetData data, 
                                  IValidateData invalidator)
        {
            this.data = data;
            this.invalidator = invalidator;          
        }
        //
        // GET: /FileUpload/

        public ActionResult Index()
        {
            var model = new UploadViewModel();
            
            model.IsFirstRowAsColumnName = true;
            return View(model);
        }        

        [HttpPost]
        public ActionResult Index(UploadViewModel model)
        {
            if (ModelState.IsValid)
            {
                var fileName = Path.GetFileName(model.File.FileName);
                if (fileName.ToUpper().EndsWith(".XLSX") || fileName.ToUpper().EndsWith(".CSV"))
                {
                    if (model.File.ContentLength > 0)
                    {                        
                        Database.CleanTable();
                        var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
                        model.File.SaveAs(path);
                                               
                        var ts = data.GetData(path,model.IsFirstRowAsColumnName);                                                                     
                        var lists = invalidator.ValidatedData(ts);                        
                        Session["Errors"] = lists;
                        Session["Count"] = ts.Count();
                        return RedirectToAction("index","Transaction");
                    }
                    return View("index");
                }
            }            
            return View("index");
        }

        public ActionResult BadTrans(int? page)
        {          
            var lists = Session["Errors"] as ValidatedTransactions;
            //if (lists != null)
            //{
                ViewBag.FailedCount = lists.FailedTransactions.Count();
                var pageNumber = page ?? 1;
                var onePageOfTransactions = lists.FailedTransactions.ToPagedList(pageNumber, 20);
                ViewBag.OnePageOfTransactions = onePageOfTransactions;
                return View();
            //}
            //return RedirectToAction("Index");
        }

    }
}

KPMGTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Styles.Render("~/Content/bootstrap")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("KPMG Excel Importor", "Index", "FileUpload")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "FileUpload")</li>
                            <li>@Html.ActionLink("Data", "Index", "Transaction")</li>
                            @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>